/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.application;

import java.security.SecureRandom;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author chris
 */
public class tesframe extends javax.swing.JFrame {
    
    DefaultTableModel dm;
    int jumlahBelanja = 0;
    int totalBelanjaan = 0;
    /**
     * Creates new form tesframe
     */
    
    public tesframe() {
        
//        SecureRandom rand = new SecureRandom();
//        int randomInt = rand.nextInt(100000);
//        System.out.println(randomInt);
        
        DBConnector.initDBConnection();
        dm = new DefaultTableModel();
        
        initComponents();
        createColumns();
        
        dm = (DefaultTableModel) barangTable.getModel();
        dm.addTableModelListener(new TableModelListener(){
            @Override
            public void tableChanged(TableModelEvent e) { 
                if(e.getColumn() == 5){
                        int baris = e.getFirstRow();
                        System.out.println("kolom ke 4");
                        String kolom4 = (String) dm.getValueAt(baris, 4);
                        float harga = Float.parseFloat(kolom4);
                        String kolom5 = (String) dm.getValueAt(baris, 5);
                        int jumlah = Integer.parseInt(kolom5);

                        float total = harga * jumlah;
                        System.out.println(harga);
                        System.out.println(total);
//                        String totalString = String.valueOf(total);
//                        String totalString2 = totalString;
                        NumberFormat formatter = new DecimalFormat("#,###,###");
                        String totalString = Float.toString(total);
                        String totalStringFormat = formatter.format(total);
                        dm.setValueAt(totalStringFormat, baris, 6);
                        dm.setValueAt(totalString, baris, 7);
                        
                        
                        float totalBelanja = 0.0f;
                        total = 0.0f;
                        
                        for (int i = 0; i < totalBelanjaan; i++){
                            String kolom7 = (String) dm.getValueAt(i, 7);
                            total = Float.parseFloat(kolom7);
                            
                            totalBelanja += total;
                            System.out.println(barangTable.getModel().getValueAt(i, 7));
                        }
                        int totalBelanjaInt = (int)totalBelanja;
//                        System.out.println(totalBelanjaInt);
                        invisibleTotalBelanjaField.setText(Float.toString(totalBelanjaInt));
//                        totalBelanjaTextField.setText(Float.toString(totalBelanjaInt));
                        
                        totalBelanjaTextField.setText(formatter.format(totalBelanjaInt));
//                        totalBelanjaTextField.setText(String.format("%,d", totalBelanjaInt));
                }
            }
        });
    }
    
    private void createColumns(){
        dm = (DefaultTableModel) barangTable.getModel();
           
        dm.addColumn("No");
        dm.addColumn("Kode");
        dm.addColumn("Nama");
        dm.addColumn("Harga Satuan");
        dm.addColumn("hargaInv");
        dm.addColumn("Jumlah");
        dm.addColumn("Total");
        dm.addColumn("totalInv");
        
        TableColumnModel tcm = barangTable.getColumnModel();
        tcm.removeColumn( tcm.getColumn(4)); //hargaInv
        tcm.removeColumn( tcm.getColumn(6)); //totalInv
    }
    
    private void populate(String no, String kode, String nama, String harga, float hargaInv, int jumlahBelanja, String total, float totalInv){
        dm = (DefaultTableModel) barangTable.getModel();
        
        String[] rowData = {no, kode, nama, harga, Float.toString(hargaInv), Integer.toString(jumlahBelanja), total, Float.toString(totalInv)};
        
        dm.addRow(rowData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kodeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        barangTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        hargaTextField = new javax.swing.JTextField();
        totalBelanjaTextField = new javax.swing.JTextField();
        dibayarTextField = new javax.swing.JTextField();
        kembalianTextField = new javax.swing.JTextField();
        clearBTN = new javax.swing.JButton();
        invisibleTotalBelanjaField = new javax.swing.JTextField();
        invisibleDibayarTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(26, 69, 224));
        jPanel1.setForeground(new java.awt.Color(33, 158, 188));

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode");

        kodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeTextFieldActionPerformed(evt);
            }
        });

        barangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        barangTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                barangTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(barangTable);

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga Barang");

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Belanja");

        jLabel6.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah yang dibayar");

        jLabel7.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kembalian");

        namaTextField.setEditable(false);
        namaTextField.setBackground(new java.awt.Color(255, 255, 255));

        hargaTextField.setEditable(false);
        hargaTextField.setBackground(new java.awt.Color(255, 255, 255));

        totalBelanjaTextField.setEditable(false);
        totalBelanjaTextField.setBackground(new java.awt.Color(255, 255, 255));

        dibayarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibayarTextFieldActionPerformed(evt);
            }
        });
        dibayarTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dibayarTextFieldKeyReleased(evt);
            }
        });

        kembalianTextField.setEditable(false);
        kembalianTextField.setBackground(new java.awt.Color(255, 255, 255));

        clearBTN.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        invisibleTotalBelanjaField.setEditable(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/application/115 asparagus.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Welcome To");

        jLabel9.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CASHIER PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(dibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(invisibleTotalBelanjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invisibleDibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clearBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kembalianTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invisibleTotalBelanjaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invisibleDibayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        invisibleTotalBelanjaField.setVisible(false);
        invisibleDibayarTextField.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        while(dm.getRowCount() > 0){
            dm.removeRow(0);
        }
        dm.setRowCount(0);
        totalBelanjaan = 0;
        kodeTextField.setText(null);
        namaTextField.setText(null);
        hargaTextField.setText(null);
        totalBelanjaTextField.setText(null);
        dibayarTextField.setText(null);
        kembalianTextField.setText(null);
        //        jlhRow.setText(null);
    }//GEN-LAST:event_clearBTNActionPerformed

    private void dibayarTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dibayarTextFieldKeyReleased
        String dibayarString = dibayarTextField.getText();
        dibayarString = dibayarString.replace(",", "");
        ////////////////////////////////////////////////////////////////////////////
        float tempDibayar = Float.parseFloat(dibayarString);
        int dibayarInput = Integer.valueOf(dibayarString);
        ////////////////////////////////////////////////////////////////////////////
        invisibleDibayarTextField.setText(Float.toString(tempDibayar));
        ////////////////////////////////////////////////////////////////////////////
        dibayarTextField.setText(String.format("%,d", dibayarInput));
    }//GEN-LAST:event_dibayarTextFieldKeyReleased

    private void dibayarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibayarTextFieldActionPerformed
        float totalBelanja = Float.valueOf(invisibleTotalBelanjaField.getText());
        int totalBelanjaInt = (int)totalBelanja;
        String totalBelanjaString = String.valueOf(totalBelanjaInt);

        float dibayar = Float.valueOf(invisibleDibayarTextField.getText());
        int dibayarInt = (int)dibayar;

        int kembalianInt = dibayarInt - totalBelanjaInt;
        kembalianTextField.setText(String.format("%,d", kembalianInt));

        if(dibayar < totalBelanja){
            kembalianTextField.setText(null);
            JOptionPane.showMessageDialog(null, "Uang Anda Kurang!", "Caution!", JOptionPane.WARNING_MESSAGE);
        }

        //time
        java.util.Date dt = new java.util.Date();
        java.text.SimpleDateFormat SDF = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = SDF.format(dt);

        String totalBelanjadb = totalBelanjaTextField.getText();
        String totalDibayardb = dibayarTextField.getText();
        String kembaliandb = kembalianTextField.getText();

        //id_transaksi
        SecureRandom rand = new SecureRandom();
        int randomInt = rand.nextInt(100000);

        //insert to transaksi
        try {
            Statement stmt = DBConnector.connection.createStatement();
            String sql = "INSERT INTO transaksi(id_transaksi, total_belanja, total_bayar, kembalian, waktu_transaksi) VALUES ('"+randomInt+"' ,'"+totalBelanjadb+"', '"+totalDibayardb+"', '"+kembaliandb+"', '"+currentTime+"')";
            stmt.execute(sql);

        } catch (Exception ex) {
            System.out.println(ex);
        }

        for(int i = 0; i<dm.getRowCount(); i++){
            String kolom1 = (String) dm.getValueAt(i, 1);
            System.out.println(kolom1);

            //detail_transaksi (id_barang dan id_transaksi)
            try {
                Statement stmt = DBConnector.connection.createStatement();
                String sql = "INSERT INTO detail_transaksi(id_barang, id_transaksi) VALUES ('"+kolom1+"', '"+randomInt+"')";
                stmt.execute(sql);

            } catch (Exception ex) {
                System.out.println(ex);
            }

        }
    }//GEN-LAST:event_dibayarTextFieldActionPerformed

    private void barangTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_barangTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_barangTablePropertyChange

    private void kodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeTextFieldActionPerformed
        String kode = kodeTextField.getText();
        String nama = "";
        float harga;
        float total;
        float hargaInv;
        float totalInv;

        try {
            Statement stmt = DBConnector.connection.createStatement();
            String sql = "select * from barang where kode='"+kode+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                NumberFormat formatter = new DecimalFormat("#,###,###");
                nama = rs.getString("nama");
                harga = rs.getFloat("harga");
                total = rs.getFloat("harga");
                hargaInv = rs.getFloat("harga");
                totalInv = rs.getFloat("harga");

                namaTextField.setText(nama);
                //                hargaTextField.setText(Float.toString(harga));
                String hargaFormat = formatter.format(harga);
                String totalFormat = formatter.format(total);
                hargaTextField.setText(formatter.format(harga));

                //                System.out.println(kode);
                //                System.out.println(nama);
                //                System.out.println(harga);
                populate(Integer.toString(dm.getRowCount()+1), kode, nama, hargaFormat, hargaInv, jumlahBelanja+1, totalFormat, totalInv);
                totalBelanjaan++;
                System.out.println("total belanjaan : "+totalBelanjaan);

                //                jlhRow.setText(Integer.toString(dm.getRowCount()));
                float totalBelanja = 0.0f;
                total = 0.0f;
                for (int i = 0; i < totalBelanjaan; i++){
                    String kolom7 = (String) dm.getValueAt(i, 7);
                    total = Float.parseFloat(kolom7);
                    totalBelanja += total;
                    //                    System.out.println(barangTable.getModel().getValueAt(i, 6));
                }
                int totalBelanjaInt = (int)totalBelanja;
                invisibleTotalBelanjaField.setText(Float.toString(totalBelanjaInt));
                totalBelanjaTextField.setText(formatter.format(totalBelanjaInt));

            }
            else{
                System.out.println("Barang Tidak Ditemukan!");
                JOptionPane.showMessageDialog(null, "Barang Tidak Ditemukan!", "Caution!", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_kodeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tesframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable barangTable;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextField dibayarTextField;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JTextField invisibleDibayarTextField;
    private javax.swing.JTextField invisibleTotalBelanjaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalianTextField;
    private javax.swing.JTextField kodeTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField totalBelanjaTextField;
    // End of variables declaration//GEN-END:variables
}
