/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.application;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class TransaksiFrame extends javax.swing.JFrame {
    
    DefaultTableModel dm;
    /**
     * Creates new form TransaksiFrame
     */
    public TransaksiFrame() {
        DBConnector.initDBConnection();
        initComponents();
        dm = new DefaultTableModel();
        dm = (DefaultTableModel) transaksiTable.getModel();
        createColumns();
        
        String waktu, idTransaksi, namaBarang, kodeBarang, totalBelanja, totalPembayaran, totalKembalian;
        
        try {
            Statement stmt = DBConnector.connection.createStatement();
//            String sql = "select * from detail_transaksi inner join transaksi on transaksi.id_transaksi = detail_transaksi.id_transaksi inner join barang on barang.kode = detail_transaksi.id_barang";
            String sql = "select *, waktu_transaksi as date from detail_transaksi inner join transaksi on transaksi.id_transaksi = detail_transaksi.id_transaksi inner join barang on barang.kode = detail_transaksi.id_barang order by date desc";  
            ResultSet rs = stmt.executeQuery(sql);

            while(rs.next()){
//                NumberFormat formatter = new DecimalFormat("#,###,###");
                waktu = rs.getString("waktu_transaksi");
                idTransaksi = rs.getString("id_transaksi");
                namaBarang = rs.getString("nama");
                kodeBarang = rs.getString("kode");
                totalBelanja = rs.getString("total_belanja");
                totalPembayaran = rs.getString("total_bayar");
                totalKembalian = rs.getString("kembalian");
                
                System.out.println(waktu);
                System.out.println(namaBarang);
                System.out.println(kodeBarang);
                System.out.println(totalBelanja);
                System.out.println(totalPembayaran);
                System.out.println(totalKembalian);
//                String hargaFormat = formatter.format(harga);
                populate(waktu, idTransaksi, namaBarang, kodeBarang, totalBelanja, totalPembayaran, totalKembalian);
            }            
        } catch (Exception ex) {
            System.out.println(ex);
        }   
    }
    
    private void createColumns(){
        dm = (DefaultTableModel) transaksiTable.getModel();
        
        dm.addColumn("Waktu Transaksi");
        dm.addColumn("ID Transaksi");
        dm.addColumn("Nama Barang");
        dm.addColumn("Kode Barang");
        dm.addColumn("Total Belanja");
        dm.addColumn("Total Pembayaran");
        dm.addColumn("Total Kembalian");
    }
    
    private void populate(String waktu, String idTransaksi, String namaBarang, String kodeBarang, String totalBelanja, String totalPembayaran, String totalKembalian){
        dm = (DefaultTableModel) transaksiTable.getModel();
        
        String[] rowData = {waktu, idTransaksi, namaBarang, kodeBarang, totalBelanja, totalPembayaran, totalKembalian};
        
        dm.addRow(rowData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 158, 188));
        jPanel1.setForeground(new java.awt.Color(33, 158, 188));

        transaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        transaksiTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(transaksiTable);

        jLabel1.setBackground(new java.awt.Color(26, 69, 224));
        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR TRANSAKSI");

        jButton1.setText("Back to admin page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new adminPage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transaksiTable;
    // End of variables declaration//GEN-END:variables
}
